version: '3'
services:
  python3:
    build: .
    container_name: 'slim-python3'
    working_dir: '/src'
    tty: true
    volumes:
      - ${SRC_PATH}:/src
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}